{
 "title": "Application",
 "description": "Service Availability",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"todo-app\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Endpoint Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top Slow Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_server_requests_seconds_sum{namespace=\"todo-app\"}[5m])) by (uri) / sum(rate(http_server_requests_seconds_count{namespace=\"todo-app\"}[5m])) by (uri))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Error Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_server_requests_seconds_count{namespace=\"todo-app\",status=~\"5..\"}[5m])) by (uri))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=\"todo-app\"}[5m])) / sum(rate(http_server_requests_seconds_count{namespace=\"todo-app\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"todo-app\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "HTTP Status Codes (2xx/4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"todo-app\"}[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"todo-app\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=~\".*\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_requests_seconds_count{namespace=\"todo-app\",status=~\"5..\"}[5m])) / sum(rate(http_server_requests_seconds_count{namespace=\"todo-app\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_active_seconds_active{namespace=\"todo-app\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}