{
 "title": "Pod-Container",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Limit Utilization %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by (pod)(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}) / sum by (pod)(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit Utilization %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by (pod)(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}) / sum by (pod)(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests & Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Requests",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (pod, container) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"$namespace\",\r\n    container!=\"\",\r\n    container!=\"POD\"\r\n  }[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 27 },
   "targets": [
    {
     "expr": "sum by (pod,container)(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\",container!=\"POD\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Pod Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (phase) (kube_pod_status_phase{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container State",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum by (container,state)(kube_pod_container_status_running{namespace=\"$namespace\"} or kube_pod_container_status_waiting{namespace=\"$namespace\"} or kube_pod_container_status_terminated{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"$namespace\",phase=\"Running\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{namespace=\"$namespace\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Terminated Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated{namespace=\"$namespace\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}