apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: todo-app

type: Opaque

stringData:
  DB_USERNAME: postgresadmin
  DB_PASSWORD: Nonsense@123
  JWT_SECRET: my-secret-key-my-secret-key-my-secret-key-123456
