{
 "title": "Database",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Database Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{job=~\".*postgres.*\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"todo_microservices_db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Connection Utilization %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pg_stat_database_numbackends{datname=\"todo_microservices_db\"} / pg_settings_max_connections) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pg_stat_database_deadlocks{datname=\"todo_microservices_db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=~\".*postgres.*\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_resident_memory_bytes{job=~\".*postgres.*\"} / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"todo_microservices_db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Utilization %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pg_database_size_bytes{datname=\"todo_microservices_db\"} / 5368709120) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"todo_microservices_db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"todo_microservices_db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"todo_microservices_db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 19 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"todo_microservices_db\"}[5m]) + rate(pg_stat_database_tup_updated{datname=\"todo_microservices_db\"}[5m]) + rate(pg_stat_database_tup_deleted{datname=\"todo_microservices_db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network & Query Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Neteork in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 28 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 28 },
   "targets": [
    {
     "expr": "rate(pg_stat_statements_mean_exec_time[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}